# backend/agents/utils/synthetic.py
import json
from langchain_groq import ChatGroq
from core.config import settings
from api.services.tss_calc import calculate_complex_tss, MODALITY_MULTIPLIERS

llm = ChatGroq(temperature=0.7, model_name="llama-3.3-70b-versatile", api_key=settings.GROQ_API_KEY)

# Get the list of allowed keys for the prompt
ALLOWED_MODALITIES = ", ".join(MODALITY_MULTIPLIERS.keys())

async def generate_synthetic_workout(modality: str, focus: str, query: str):
    # Fallback to 'Conditioning' if the LLM hallucinated a modality not in our dict
    validated_modality = modality if modality in MODALITY_MULTIPLIERS else "Conditioning"
    
    prompt = f"""
    Create a unique 60-minute workout.
    MODALITY: {validated_modality} (You MUST ONLY use this modality).
    FOCUS: {focus}
    GOAL: {query}
    
    STRICT RULES:
    1. Modality must be one of: [{ALLOWED_MODALITIES}].
    2. Intensity Factor (IF) must be between 0.3 and 1.2, unless it is a rest day, then IF should be 0.
    3. Output ONLY raw JSON.

    STRUCTURE FORMAT (List of blocks with steps):
    {{
      "title": "Name",
      "description": "Overview",
      "structure": [
        {{
          "name": "Block Name",
          "repeat_count": 1,
          "steps": [
            {{"name": "Warmup", "duration_mins": 10, "intensity_factor": 0.4}}
          ]
        }}
      ]
    }}
    """
    try:
        response = await llm.ainvoke(prompt)
        clean_content = response.content.replace('```json', '').replace('```', '').strip()
        data = json.loads(clean_content)
        
        # 🔥 THE PRO MOVE: Use your real Python function for the math
        # This replaces the AI's "guess" with your actual formula
        data["tss"] = calculate_complex_tss(data["structure"], validated_modality)
        
        return data
    except Exception as e:
        print(f"Synthetic Error: {e}")
        return {
            "title": f"Custom {validated_modality} Session",
            "description": "Dynamic session generated by AI.",
            "structure": [{"name": "Main", "repeat_count": 1, "steps": [{"name": "Steady State", "duration_mins": 60, "intensity_factor": 0.6}]}],
            "tss": 45.0
        }
