"""remove legacy rpe column

Revision ID: a5ad372a29be
Revises: be166ddd0c37
Create Date: 2026-02-22 16:09:03.568514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ad372a29be'
down_revision: Union[str, Sequence[str], None] = 'be166ddd0c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'rpe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('rpe', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
