"""refactor user_plans to macro architecture

Revision ID: be166ddd0c37
Revises: ec39889068f8
Create Date: 2026-02-22 15:23:43.019658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be166ddd0c37'
down_revision: Union[str, Sequence[str], None] = 'ec39889068f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_plans', sa.Column('plan_name', sa.String(), nullable=True))
    op.add_column('user_plans', sa.Column('user_goal', sa.String(), nullable=False))
    op.add_column('user_plans', sa.Column('calendar_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('user_plans', sa.Column('coach_reasoning', sa.String(), nullable=True))
    op.add_column('user_plans', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('user_plans_user_id_fkey'), 'user_plans', type_='foreignkey')
    op.drop_constraint(op.f('user_plans_workout_id_fkey'), 'user_plans', type_='foreignkey')
    op.create_foreign_key(None, 'user_plans', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_plans', 'day_index')
    op.drop_column('user_plans', 'is_user_locked')
    op.drop_column('user_plans', 'workout_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_plans', sa.Column('workout_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('user_plans', sa.Column('is_user_locked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user_plans', sa.Column('day_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_plans', type_='foreignkey')
    op.create_foreign_key(op.f('user_plans_workout_id_fkey'), 'user_plans', 'workouts', ['workout_id'], ['id'])
    op.create_foreign_key(op.f('user_plans_user_id_fkey'), 'user_plans', 'users', ['user_id'], ['id'])
    op.drop_column('user_plans', 'created_at')
    op.drop_column('user_plans', 'coach_reasoning')
    op.drop_column('user_plans', 'calendar_data')
    op.drop_column('user_plans', 'user_goal')
    op.drop_column('user_plans', 'plan_name')
    # ### end Alembic commands ###
